#!/bin/sh

printf "\e[0;32m### Kubectl version ###\e[m\n"
kubectl version --client

printf "\n\e[0;32m### Terraform version ###\e[m\n"
terraform version

printf "\n\e[0;32m### Istioctl version ###\e[m\n"
istioctl version --remote=false

printf "\n\e[0;32m### Helm version ###\e[m\n"
helm version

printf "\n\e[0;32m### Kyma version ###\e[m\n"
kyma version

printf "\n\e[0;32m### Modulectl version ###\e[m\n"
modulectl version

printf "\n\e[0;32m### BTP version ###\e[m\n"
btp --version
